export {default as About} from './About'
export {default as Certification} from './Certification'
export {default as Contact} from './Contact'
export {default as Footer} from './Footer'
export {default as Home} from './Home'
export {default as NavBar} from './NavBar'
export {default as Portfolio} from './Portfolio'
export {default as Skills} from './Skills'
